apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  error-log-level: debug
  enable-opentelemetry: "true"
  opentelemetry-collector-host: "my-opentelemetry-collector.default.svc.cluster.local"
  opentelemetry-collector-port: "4317"
  opentelemetry-service-name: "nginx-ingress"