mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.102.0

presets:
  # This enables pod log collection and ignores OTel Collector logs.
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  # This enables host metric collection.
  hostMetrics:
    enabled: true
  # This adds Kubernetes metadata to logs and metrics.
  kubernetesAttributes:
    enabled: true

config:
  extensions: 
    health_check: {}
  connectors:
    datadog/connector:
      traces:
        span_name_as_resource_name: true
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:2000
  processors:
    batch:
      timeout: 1s  # Optional: Maximum time to wait before sending a batch, default is 200ms
      send_batch_size: 512  # Optional: Maximum number of items to batch, default is 8192
    resource:
      attributes:
        - key: deployment.environment
          value: production
          action: upsert
    transform:
      log_statements:
        - context: resource
          statements:
            - set(attributes["custom_attribute"],"My Custom Value!")
  exporters:
    logging:
      loglevel: debug
    datadog:
      traces:
        span_name_as_resource_name: true
        trace_buffer: 500
      api:
        key: "${DD_API_KEY}"
      hostname: ${env:K8S_NODE_NAME}
      host_metadata:
        enabled: true
        hostname_source: config_or_system
    debug:
      verbosity: detailed
  service:
    extensions: 
      - health_check
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [debug, logging, datadog, datadog/connector]
      metrics:
        receivers: [hostmetrics, otlp, datadog/connector]
        processors: [batch, resource]
        exporters: [debug, logging, datadog]
      logs:
        receivers: [otlp, filelog]
        processors: [resource, batch, transform]
        exporters: [debug, logging, datadog]

extraEnvs:
  - name: DD_API_KEY
    valueFrom:
      secretKeyRef:
        name: datadog-api-key
        key: api-key
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName 

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

readinessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3