apiVersion: v2                 # Defines the Helm chart API version (v2 is standard for Helm 3)
name: flask-otel               # The name of your Helm chart
description: A Helm chart for deploying Flask with OpenTelemetry instrumentation
version: 0.1.0                 # Version of your chart
appVersion: "1.0.0"   